# Generated by Django 6.0.3 on 2026-03-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_priority_box_folder_box_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='task_app.workspace'),
        ),
    ]
