# Generated by Django 6.0.3 on 2026-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_workspacemember_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_space',
            field=models.CharField(choices=[('one', 'Just me'), ('two-five', '2-5'), ('six-fifteen', '6-15')], default='one', max_length=16),
        ),
    ]
