# Generated by Django 6.0.3 on 2026-03-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_workspace_workspace_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='workspace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.workspace'),
        ),
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(choices=[('#123F73', '🔵Deep ocean'), ('#D2A1FE', '🟣Violet'), ('#33DEB8', '🟢Aquamarine'), ('#6D020E', '🔴Red wine'), ('#FCF6A7', '🟡Sand'), ('#774C06', '🟤Terracotta'), ('#000000', '⚫Black')], default='#000000', max_length=32),
        ),
    ]
