# Generated by Django 6.0.3 on 2026-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_folder_workspace_alter_box_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(choices=[('#123F73', '🔵Deep ocean'), ('#D2A1FE', '🟣Violet'), ('#33DEB8', '🟢Aquamarine'), ('#6D020E', '🔴Red wine'), ('#FCF6A7', '🟡Sand'), ('#774C06', '🟤Terracotta'), ('#000000', '⚫Black')], default='#123F73', max_length=32),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
