# Generated by Django 6.0.3 on 2026-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_alter_box_color_alter_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(choices=[('#77acc7', '🔵Air blue'), ('#9966cc', '🟣Amethust'), ('#008000', '🟢Apple Green'), ('#ff033e', '🔴Red rose'), ('#ffe135', '🟡Banana yellow'), ('#ff6500', '🟠Sunset'), ('#000000', '⚫Black')], default='#77acc7', max_length=30),
        ),
    ]
