# Generated by Django 6.0.3 on 2026-04-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_alter_folder_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='box',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='task_app.box'),
        ),
    ]
