# Generated by Django 6.0.3 on 2026-04-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_folder_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='invite_role',
            field=models.CharField(choices=[('owner_only', 'Only owner'), ('owner_admin', 'Owner & Admin')], default='owner_admin', max_length=16),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_space',
            field=models.CharField(choices=[('one', 'Just me'), ('two_five', 'Group (2-5)'), ('six_fifteen', 'Team (6-15)')], default='one', max_length=16),
        ),
    ]
