# Generated by Django 6.0.3 on 2026-04-24 21:26

import task_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_workspaceinvite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspaceinvite',
            name='unique_pending_invite_per_email',
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='code',
            field=models.CharField(default=task_app.models.generate_invite_code, max_length=9, unique=True),
        ),
        migrations.RemoveField(
            model_name='workspaceinvite',
            name='email',
        ),
    ]
