# Generated by Django 6.0.3 on 2026-05-06 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_remove_workspaceinvite_unique_pending_invite_per_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('task_created', 'Task created'), ('task_delete', 'Task delete'), ('task_status_changed', 'Task status changed'), ('task_priority_changed', 'Task priority changed'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_role_changes', 'Member role changes'), ('folder_created', 'Folder created'), ('folder_deleted', 'Folder deleted')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_log', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task_app.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
