# Generated by Django 6.0.3 on 2026-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_alter_workspacelog_action_alter_workspacelog_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacelog',
            name='action',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_deleted', 'Task deleted'), ('task_status_changed', 'Task status changed'), ('task_priority_changed', 'Task priority changed'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_role_changed', 'Member role changed'), ('folder_created', 'Folder created'), ('folder_deleted', 'Folder deleted'), ('box_created', 'Box created'), ('box_deleted', 'Box deleted')], max_length=32),
        ),
    ]
